repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

# fork of the below, didn't seem to work...
# -   repo: https://github.com/FeryET/pre-commit-rust
#     rev: v1.0.3
#     hooks:
#     -   id: fmt
#     -   id: cargo-check

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
