[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {workspace = true}
log = {workspace = true}

crossterm = "0.29.0"
rand = "0.9.1"
chrono = "0.4.40"
